const tasks = [
  {
    id: 'daily-checkin',
    titleKey: 'tasks.dailyCheckin.title',
    descriptionKey: 'tasks.dailyCheckin.desc',
    type: 'daily',
    category: 'daily',
    tags: ['practice'],
    priority: 'medium',
    trigger: 'manual',
    cooldownHours: 24,
    target: 1,
    rewards: { points: 20, badges: ['first-task'] },
    visibility: 'public',
  },
  {
    id: 'drill',
    titleKey: 'tasks.drill.title',
    descriptionKey: 'tasks.drill.desc',
    type: 'event',
    category: 'practice',
    tags: ['practice', 'emergency'],
    priority: 'high',
    trigger: 'manual',
    target: 1,
    rewards: { points: 80, badges: [] },
    visibility: 'public',
  },
  {
    id: 'kit-check',
    titleKey: 'tasks.kitCheck.title',
    descriptionKey: 'tasks.kitCheck.desc',
    type: 'checklist',
    category: 'preparation',
    tags: ['preparation', 'emergency'],
    priority: 'high',
    trigger: 'manual',
    target: 1,
    rewards: { points: 50, badges: [] },
    visibility: 'public',
  },
  {
    id: 'first-emergency-kit',
    titleKey: 'tasks.firstKit.title',
    descriptionKey: 'tasks.firstKit.desc',
    type: 'milestone',
    category: 'preparation',
    tags: ['preparation', 'emergency'],
    priority: 'medium',
    trigger: 'event',
    target: 1,
    rewards: { points: 30, badges: [] },
    visibility: 'public',
  },
  {
    id: 'knowledge-basics',
    titleKey: 'tasks.knowledgeBasics.title',
    descriptionKey: 'tasks.knowledgeBasics.desc',
    type: 'learning',
    category: 'learning',
    tags: ['knowledge', 'learning'],
    priority: 'medium',
    trigger: 'manual',
    target: 1,
    rewards: { points: 40, badges: [] },
    visibility: 'public',
  },
  {
    id: 'quiz-complete',
    titleKey: 'tasks.quizComplete.title',
    descriptionKey: 'tasks.quizComplete.desc',
    type: 'learning',
    category: 'learning',
    tags: ['knowledge', 'learning'],
    priority: 'low',
    trigger: 'manual',
    target: 1,
    rewards: { points: 60, badges: [] },
    visibility: 'public',
  },
  {
    id: 'community-help',
    titleKey: 'tasks.communityHelp.title',
    descriptionKey: 'tasks.communityHelp.desc',
    type: 'event',
    category: 'community',
    tags: ['community', 'practice'],
    priority: 'medium',
    trigger: 'manual',
    target: 1,
    rewards: { points: 70, badges: [] },
    visibility: 'public',
  },
  {
    id: 'weekly-review',
    titleKey: 'tasks.weeklyReview.title',
    descriptionKey: 'tasks.weeklyReview.desc',
    type: 'weekly',
    category: 'review',
    tags: ['practice'],
    priority: 'low',
    trigger: 'manual',
    cooldownHours: 168,
    target: 1,
    rewards: { points: 100, badges: [] },
    visibility: 'public',
  },
];

export const TASK_CATEGORIES = {
  all: 'tasks.category.all',
  daily: 'tasks.category.daily',
  weekly: 'tasks.category.weekly',
  preparation: 'tasks.category.preparation',
  learning: 'tasks.category.learning',
  practice: 'tasks.category.practice',
  community: 'tasks.category.community',
  review: 'tasks.category.review',
};

export const TASK_TAGS = {
  preparation: 'tasks.tag.preparation',
  knowledge: 'tasks.tag.knowledge',
  practice: 'tasks.tag.practice',
  emergency: 'tasks.tag.emergency',
  community: 'tasks.tag.community',
  learning: 'tasks.tag.learning',
};

export const TASK_PRIORITIES = {
  high: 'tasks.priority.high',
  medium: 'tasks.priority.medium',
  low: 'tasks.priority.low',
};

export const TASK_SORT_OPTIONS = {
  newest: 'tasks.sort.newest',
  oldest: 'tasks.sort.oldest',
  priority: 'tasks.sort.priority',
  progress: 'tasks.sort.progress',
};

export default tasks;
